name: _Test OCI Factory
on:
  push:
    paths:
      - ".github/workflows/*"
      - "oci/mock-*"
      - "examples/*"
      - "src/*"

jobs:
  test-workflows:
    name: Test OCI Factory workflows
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        oci-image: [mock-rock, mock-docker-image]
    steps:
      - name: Trigger image workflows for ${{ matrix.oci-image }}
        id: run-images
        uses: pauldraper/workflow-dispatch@v1.5
        with:
          marker-input: ${{ github.run_id }}_${{ matrix.oci-image }}
          workflow: Image.yaml
          inputs: '{ "oci-image-name": "${{ matrix.oci-image }}", "upload": true }'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          wait: true
        # # Using this actions cause others can have this problem:
        # # https://github.com/convictional/trigger-workflow-and-wait/issues/61
        # uses: mathze/workflow-dispatch-action@v1.2.0
        
        # with:
        #   token: ${{ secrets.ROCKSBOT_TOKEN }}
        #   ref: ${{ github.ref }}
        #   # fail-on-error: true
        #   workflow-name: Image.yaml
        #   payload: '{ "oci-image-name": "${{ matrix.oci-image }}", "upload": true }'
        #   # trigger-timeout: "1m"
        #   # use-marker-step: true
        #   # run-id: dummy
        #   # wait-timeout: "30m"

      # - name: Wait for image workflows
      #   uses: mathze/workflow-dispatch-action@v1.2.0
      #   id: wait-images
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     run-id: ${{ steps.run-images.outputs.run-id }}
      #     wait-interval: 10s
      #     # fail-on-error: true
      #     wait-timeout: "30m"

      - run: exit ${{ steps.run-images.outputs.conclusion == 'success' && 1 || 0 }}
